"""Provider contracts (DESIGN §7). Stubs now; Yahoo/ESPN adapters in Phase 8
implement exactly these and nothing downstream changes."""
from __future__ import annotations

from typing import AsyncIterator, Protocol

from ..models import Game, League, Matchup, Player, PlayRow, Roster


class LeagueProvider(Protocol):
    def league(self) -> League: ...
    def roster(self, team_key: str, week: int) -> Roster: ...
    def matchup(self, team_key: str, week: int) -> Matchup: ...
    def matchups(self, week: int) -> list[Matchup]: ...
    def official_points(self, team_key: str, week: int) -> dict[str, float]: ...


class PlayProvider(Protocol):
    def live_games(self) -> list[Game]: ...
    def stream_plays(self) -> AsyncIterator[PlayRow]: ...


class PlayerDirectory(Protocol):
    def player(self, player_id: str) -> Player | None: ...
    def by_short(self, short: str, team: str | None = None) -> Player | None: ...
